name: binance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.5

  firebase_core: ^3.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.14
  fluttertoast: ^8.2.8
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/WhatsApp Image 2024-11-14 at 2.08.51 PM.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: BinancePlex
      fonts:
        - asset: assets/fonts/binance.ttf
